services:
  qdrant:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    container_name: homework-lesson-10-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: homework-lesson-10-app
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
    command: npm run dev

volumes:
  qdrant_storage:
  app_node_modules:
